name: deploy to lambda
on: [push]
jobs:
  deploy_source:
    name: build and deploy lambda
    strategy:
      matrix:
        node-version: [14.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          persist-credentials: false
          working-directory: ./Back
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          working-directory: ./Back
          node-version: ${{ matrix.node-version }}
      - name: npm init
        working-directory: ./Back
        run: npm init -y
      - name: npm install and build
        working-directory: ./Back
        run: |
          npm install
          npm run build --if-present
        env:
          working-directory: ./Back
          CI: true
      - name: zip
        uses: montudor/action-zip@v0.1.0
        with:
          working-directory: ./Back
          args: zip -qq -r ./bundle.zip ./
      - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          working-directory: ./Back
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: sa-east-1
          function_name: ATMsimulator
          zip_file: bundle.zip
